image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
name: mldesigner_environment
conda_file:
  name: default_environment
  channels:
    - defaults
  dependencies:
    - python=3.8.12
    - pip=21.2.2
    - pip:
      - mldesigner==0.1.0b4
      - chess==1.9.4
      - pandas==1.5.2
      - numpy==1.23.3
      - tensorflow==2.11.0
      - sklearn==1.2.0